language: ruby
rvm:
- 2.2.3
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproof ./_site --only-4xx
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: awkale
  - EMAIL: hi@awkale.me
  - secure: LfxsHXCY/h1EP2ChKWHU7Ccizr7Ege0qbr3Bmx9Cn513iQQtSRRXQLyQ85uGeQ2okyNW6NKFk/3qLt2Ltw0wut8VKWBKY8wU1bE57ZOgKPIAx4OVrb9RIOOLRzVvxPdiHE8NccOMQZAsAFoKmywDjruQOTZryU6nYxlQdIbu/iSLvWm6t1lyEHMJYKqUtQI9EQHYm6GiyR4eQIOxgs3i43YRe2pt0mJPx/wJRekgmtL/slPfaWWxn5QSe1YlXNxMHBGOg9e2dnMGhZChfK5sHdoFctH2qzcmFqojKjb3wtZpQdCQVMiSY/SGRrs8HGOckCNB5BqQI1fPH2o+JPG6cGkPKny6RAP1zf1le3BQRLRrMBIwPiFyWNOfegQZLQUna+qOurBL0xgCk/+O079zvAPfpoX0OPxJC+/57cLIt7qYvHBd4UViahV+0/GRiNLfvSTK7bCeloHRsftgqOkjx10B7IXSmDdcu6Bmpi7Qxi49Q74gWfeYXpKLS9DciO5jVaUbHNdDr5SJrXgxlWw7e2V+lPYhxT0MCK30TXY0nW9K9s8V/BWDmu1jQSv+zrBgwyILpD24k7NgETvAcKTHU5woEo3BPg2zuTqYPYnK7i5F6ZbxHLg9wu6sWcnG2lT98jLVaRjjUjGee/lw3VgMkfQiQD9i71bnAugztLCjCwQ=
notifications:
  email: false
  slack:
    secure: iujTKk9ZuJH3AW/7B81oMzSFCFIgU2xBxAijfLyJarcSOT5AYRi27Crr9zeehx9rchsD+frj//uily91FLfpDUqT295R7RIPf7e503B1OlI9FHxp7GSNS0+A1cp3INXCmYUfwrRsNcvL6qxa1gW8Zr9NRVrQTMzmGdZq/RwaeEEm4RhSyzVrvsSsNVc1d/eSEt2Y0lmaAY3L6cywwGJYsPXTa20/mTLgHzikBhy47jU2nbX7TwyP3eQR1JMiOnrnHHDi6ZrWh4zsMvwx2nM4fruO2UcJahGBDvU7n/UY2XgtjxORt9gIeLMzQZwyEXBRyOjt2+7yvd49aNmnbFcLF26svHXpPWfT1Udm1gK2olUwZGP7Ore4FBRFGs2AQnsN0iydmkAdj0n4BPxS/v1oyQ3UEVDXDrS/wUCDldEEN0TlNf6SahzP8/wv1CKDk7MwLxqbNz1tnp0fhs9DpoASvO6aON7eLYq4WSv4E+KSRmDXHa9EBl2bOhEANUP+VAYyf+bwoz53GkuQMOsgK7+iV9K0I82mEGGGprDwrBRiLBYMtiD8RJQ2ogiZY4S7YxqZ7pMPiMQ/Cl/o6DPugr9/ye/tPJlQFq6dirZaH3s+2VVaBldD82T4Wu18Tyz+uo5r+uCH8Q/eUaBcHEDNYNECqjIoTmXBS8uMJNTHnZjis/M=
