assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

collections:
  components:
    output: true
    permalink: components/:path/

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-assets
  - jekyll-sitemap

name: styleguide

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

url: # add site url



